import * as si from "simple-icons";
import * as Lucide from "lucide-react";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "..", "src", "lib", "generated-icons.ts");

const cap = (s) =>
  s.split("-").map((p) => (p ? p[0].toUpperCase() + p.slice(1) : p)).join("");

const BRAND_SLUGS = [
  "react", "nextdotjs", "vuedotjs", "svelte", "angular", "nodedotjs",
  "javascript", "typescript", "python", "java", "go", "rust",
  "html5", "css", "tailwindcss", "docker", "kubernetes", "terraform",
  "git", "github", "gitlab", "postgresql", "mongodb", "mysql",
  "sqlite", "redis", "graphql", "amazonaws", "googlecloud", "azuredevops",
  "tensorflow", "pytorch", "numpy", "pandas", "django", "flask",
  "express", "spring", "dotnet", "swift", "kotlin", "linux", "ubuntu",
  "instagram", "x", "youtube", "facebook", "tiktok", "figma",
  "apple", "android", "notion", "slack", "discord", "zoom",
  "bitcoin", "ethereum", "npm", "pnpm", "vercel", "markdown",
  "microsoft", "google", "cloudflare", "github", "git",
];

const LINE_NAMES = [
  "brain", "target", "rocket", "trending-up", "shield-check", "lock",
  "key", "lightbulb", "book-open", "book", "wrench", "sparkles",
  "heart", "activity", "clock", "camera", "play", "globe",
  "layers", "users", "message-circle", "zap", "server", "cloud",
  "database", "code", "file-code", "terminal", "cpu", "network",
  "line-chart", "pie-chart", "flower-2", "sprout", "palette", "settings",
  "bell", "calendar", "mail", "phone", "shopping-cart", "music",
  "film", "gamepad-2", "dumbbell", "coffee", "star", "award",
  "crown", "gem", "wallet", "banknote", "gift", "party-popper",
  "flag", "graduation-cap", "school", "ruler", "pen-tool", "type",
  "moon", "sun", "anchor", "compass", "map", "mountain",
  "tree-pine", "utensils", "building-2", "factory", "truck", "plane",
  "car", "stethoscope", "pill", "flask-conical", "atom", "microscope",
  "leaf", "flower", "heart-pulse", "bar-chart-3", "sparkle", "star",
];

const brands = [];
for (const slug of BRAND_SLUGS) {
  const icon = si["si" + cap(slug)];
  if (!icon) {
    console.warn("skip brand (not in simple-icons):", slug);
    continue;
  }
  brands.push({ id: slug, title: icon.title, hex: icon.hex, d: icon.path });
}

const lines = [];
for (const name of LINE_NAMES) {
  const Component = Lucide[cap(name)];
  if (!Component) {
    console.warn("skip line icon (not in lucide-react):", name);
    continue;
  }
  const svg = renderToStaticMarkup(
    React.createElement(Component, { size: 24, "aria-hidden": "true" })
  );
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  lines.push({ id: name, title: name, svg: inner });
}

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit.
// simple-icons (brands) + lucide-react (line icons), flattened to raw SVG data.

export interface BrandIcon {
  id: string;
  title: string;
  hex: string;
  d: string;
}

export interface LineIcon {
  id: string;
  title: string;
  svg: string;
}

export const BRAND_ICONS: BrandIcon[] = ${JSON.stringify(brands, null, 2)};

export const LINE_ICONS: LineIcon[] = ${JSON.stringify(lines, null, 2)};

export type IconLibrary = Record<string, BrandIcon | LineIcon>;

export const ALL_ICONS: IconLibrary = (() => {
  const lib: IconLibrary = {};
  for (const i of BRAND_ICONS) lib[i.id] = i;
  for (const i of LINE_ICONS) lib[i.id] = i;
  return lib;
})();
`;

fs.writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${brands.length} brands, ${lines.length} line icons`);
